"""change_url_to_string

Revision ID: 1fec31a2ee96
Revises: 17693d871396
Create Date: 2026-09-26 01:56:13.010837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fec31a2ee96'
down_revision: Union[str, Sequence[str], None] = '17693d871396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'url',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=511),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'url',
               existing_type=sa.String(length=511),
               type_=sa.BOOLEAN(),
               existing_nullable=False)
    # ### end Alembic commands ###
