"""add review run idempotency constraint

Revision ID: 9671c39e9c26
Revises: 018dba06323e
Create Date: 2026-10-01 15:56:50.704269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9671c39e9c26'
down_revision: Union[str, Sequence[str], None] = '018dba06323e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_review_runs_pull_request_commit', 'review_runs', ['pull_request_id', 'commit_sha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_runs_pull_request_commit', 'review_runs', type_='unique')
    # ### end Alembic commands ###
