"""add pull request diff

Revision ID: e6cbbf8e263c
Revises: a1f7bb1d53e9
Create Date: 2026-09-26 16:53:21.482854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6cbbf8e263c'
down_revision: Union[str, Sequence[str], None] = 'a1f7bb1d53e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('diff', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'diff')
    # ### end Alembic commands ###
